"use client";

import { useState } from "react";
import { ArrowRight, Check, Crosshair, Gamepad2, MessageSquare, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import type { Language } from "@/lib/marketing";

export function PlayingMethods({ lang, selected, onSelect }: { lang: Language; selected: "duo" | "piloted"; onSelect: (method: "duo" | "piloted") => void }) {
  const ru = lang === "ru";
  return <section className="content-block playing-section"><div className="wrap"><div className="section-heading"><div><span className="kicker">DUO / PILOTED</span><h2>{ru ? "Ваш стиль. Ваш формат." : "Your game. Your way."}</h2></div><p>{ru ? "Присоединяйтесь к матчам или согласуйте выполнение на аккаунте. Формат выбираете вы." : "Join the matches or arrange a piloted order. Choose the format that works for you."}</p></div><div className="playing-grid">
    <article className={selected === "duo" ? "playing-card selected" : "playing-card"}><div className="playing-art duo-art" aria-hidden="true"><div><UserRound size={30}/><span>{ru ? "ВЫ" : "YOU"}</span></div><span className="team-link">+</span><div><Crosshair size={30}/><span>{ru ? "ИСПОЛНИТЕЛЬ" : "BOOSTER"}</span></div><span className="art-caption">DUO QUEUE</span></div><div className="playing-copy"><span className="format-label"><UsersRound size={16}/> DUO</span><h3>{ru ? "Играйте вместе" : "Play together"}</h3><p>{ru ? "Вы остаётесь в игре и проходите матчи вместе с исполнителем. Заранее согласуйте регион и удобное время." : "Stay in the game and play alongside the booster. Agree on your region and available times first."}</p><ul><li><Check size={15}/>{ru ? "Доступ к аккаунту остаётся у вас" : "You keep access to your account"}</li><li><Check size={15}/>{ru ? "Расписание по договорённости" : "An agreed playing schedule"}</li></ul><button onClick={() => onSelect("duo")} className="format-select">{ru ? "Выбрать совместную игру" : "Choose duo play"}<ArrowRight size={17}/></button></div></article>
    <article className={selected === "piloted" ? "playing-card selected" : "playing-card"}><div className="playing-art piloted-art" aria-hidden="true"><Gamepad2 size={65}/><div className="art-target"><span>{ru ? "ВАША ЦЕЛЬ" : "YOUR GOAL"}</span><strong>PREMIER / FACEIT</strong><div><i/><i/><i/><i/><i/></div></div><span className="art-caption">PILOTED</span></div><div className="playing-copy"><span className="format-label"><Gamepad2 size={16}/> PILOTED</span><h3>{ru ? "Поручите выполнение" : "Arrange piloted play"}</h3><p>{ru ? "Исполнитель играет на аккаунте по согласованным условиям. Обсудите порядок доступа с администратором до начала работы." : "The booster plays on the account under agreed conditions. Discuss access arrangements with the admin before starting."}</p><ul><li><Check size={15}/>{ru ? "Цель и срок фиксируются в заказе" : "Goal and deadline recorded in the order"}</li><li><Check size={15}/>{ru ? "Статус и связь в личном кабинете" : "Status and chat in your account"}</li></ul><button onClick={() => onSelect("piloted")} className="format-select">{ru ? "Выбрать выполнение на аккаунте" : "Choose piloted play"}<ArrowRight size={17}/></button></div></article>
  </div></div></section>;
}

export function AccountShowcase({ lang }: { lang: Language }) {
  const ru = lang === "ru";
  const [step, setStep] = useState(1);
  const labels = ru ? ["Заявка", "Предложение", "В работе", "Завершён"] : ["Request", "Offer", "In progress", "Completed"];
  const descriptions = ru ? ["Выберите площадку, рейтинг и формат игры. Заявка сохранится в вашем кабинете.", "Цена уже рассчитана. После принятия заявки оплатите её и передайте данные в защищённой форме.", "Пишите в чат заказа и следите за статусом. Обновления публикует администратор.", "Обсудите результат с администратором. История условий и переписки останется в кабинете."] : ["Choose a platform, rating and playing method. Your request is saved in your account.", "Your price is already calculated. After acceptance, pay and submit your details in the secure form.", "Use the order chat and follow its status. Updates are posted by the admin.", "Review the result with the admin. Your order terms and conversation remain in your account."];
  return <section className="content-block alt account-showcase" id="process"><div className="wrap showcase-grid"><div><span className="kicker">{ru ? "ОТ ЗАЯВКИ ДО РЕЗУЛЬТАТА" : "FROM REQUEST TO RESULT"}</span><h2>{ru ? "Всё по заказу — в одном месте." : "Your order, all in one place."}</h2><p>{ru ? "Не нужно искать договорённости среди разных переписок. Условия, статус и чат доступны в личном кабинете." : "Keep agreements out of scattered conversations. Terms, status and chat are together in your account."}</p><div className="journey-tabs" role="tablist" aria-label={ru ? "Этапы заказа" : "Order stages"}>{labels.map((label, index) => <button key={label} id={`stage-${index}`} role="tab" aria-selected={step === index} aria-controls="stage-description" onClick={() => setStep(index)}><span>0{index + 1}</span>{label}<ArrowRight size={15}/></button>)}</div><p id="stage-description" role="tabpanel" aria-labelledby={`stage-${step}`} className="stage-description">{descriptions[step]}</p></div><div className="account-preview"><div className="preview-heading"><div><span className="preview-dot"/><strong>CS2 BOOST / {ru ? "КАБИНЕТ" : "ACCOUNT"}</strong></div><span>{ru ? "Пример интерфейса" : "Interface preview"}</span></div><div className="preview-body"><div className="preview-order"><span>PREMIER</span><span className={`status status-${["new", "awaiting_payment", "in_progress", "completed"][step]}`}>{labels[step]}</span></div><h3>{ru ? "Ваша следующая цель" : "Your next goal"}</h3><div className="preview-rating"><strong>4 500</strong><ArrowRight size={24}/><strong>10 000</strong></div><div className="preview-track">{labels.map((label, index) => <div className={index <= step ? "done" : ""} key={label}><i>{index < step ? <Check size={12}/> : index + 1}</i><small>{label}</small></div>)}</div><div className="preview-terms"><span>{ru ? "Цена и срок" : "Price and deadline"}</span><strong>{ru ? "2 750 ₽ · 6 дней" : "2,750 RUB · 6 days"}</strong></div><div className="preview-chat"><MessageSquare size={20}/><div><strong>{ru ? "Чат с администратором" : "Admin conversation"}</strong><p>{ru ? "Вопросы и договорённости рядом с заказом." : "Questions and agreements beside your order."}</p></div></div><div className="preview-note"><ShieldCheck size={15}/>{ru ? "Условия подтверждаются до оплаты" : "Terms confirmed before payment"}</div></div></div></div></section>;
}
