"use client";

import { useState, type CSSProperties } from "react";
import { ArrowRight, ArrowUpRight, Check, Crosshair, LockKeyhole, MessageSquare, ShieldCheck, Timer, UserRound } from "lucide-react";
import type { Language } from "@/lib/marketing";

export function PlayingMethods({ lang, selected, onSelect }: { lang: Language; selected: "duo" | "piloted"; onSelect: (method: "duo" | "piloted") => void }) {
  const ru = lang === "ru";
  return <section className="tactical-section playing-section"><div className="wrap"><div className="section-heading"><div><span className="kicker">03 // GAME MODE</span><h2>{ru ? "В игре. Или за кадром." : "In the game. Or behind the scenes."}</h2></div><p>{ru ? "Играйте вместе с исполнителем или поручите ему выполнение. Выбирайте удобный для себя формат." : "Play alongside the booster or let them handle the matches. Choose the format that fits you."}</p></div><div className="playing-grid">
    {(["duo", "piloted"] as const).map(mode => <article className={`playing-card${selected === mode ? " selected" : ""}`} key={mode}><div className="mode-card-header"><span>MODE / {mode === "duo" ? "01" : "02"}</span>{selected === mode && <span className="mode-selected"><Check size={12}/>{ru ? "ВЫБРАН" : "SELECTED"}</span>}</div><div className="mode-identity"><div><span className="format-label">{mode.toUpperCase()}</span><h3>{mode === "duo" ? (ru ? "Играйте вместе" : "Play together") : (ru ? "Поручите выполнение" : "Piloted play")}</h3></div><div className="mode-diagram" aria-hidden="true"><div>{mode === "duo" ? <UserRound size={22}/> : <LockKeyhole size={22}/>}<span>{mode === "duo" ? (ru ? "ВЫ" : "YOU") : "ACCOUNT"}</span></div><span className="mode-connector"><ArrowRight size={16}/></span><div><Crosshair size={22}/><span>{ru ? "ИСПОЛНИТЕЛЬ" : "BOOSTER"}</span></div></div></div><p>{mode === "duo" ? (ru ? "Вы играете со своего аккаунта в одной команде с исполнителем." : "You play on your own account, on the same team as the booster.") : (ru ? "Исполнитель играет на аккаунте по согласованным с вами условиям." : "The booster plays on the account under terms agreed with you.")}</p><dl className="mode-specs"><div><dt>{ru ? "Доступ к аккаунту" : "Account access"}</dt><dd>{mode === "duo" ? (ru ? "Остаётся у вас" : "Stays with you") : (ru ? "Передаётся исполнителю" : "Shared with the booster")}</dd></div><div><dt>{ru ? "Расписание" : "Schedule"}</dt><dd>{mode === "duo" ? (ru ? "Согласуем вместе" : "Agreed together") : (ru ? "Без вашего участия" : "Without joining matches")}</dd></div><div><dt>{ru ? "Связь" : "Communication"}</dt><dd>{ru ? "Чат заказа" : "Order chat"}</dd></div></dl><button type="button" aria-pressed={selected === mode} onClick={() => onSelect(mode)} className="format-select">{mode === "duo" ? (ru ? "Выбрать DUO" : "Choose DUO") : (ru ? "Выбрать PILOTED" : "Choose PILOTED")}<ArrowUpRight size={18}/></button></article>)}
  </div></div></section>;
}

export function AccountShowcase({ lang }: { lang: Language }) {
  const ru = lang === "ru";
  const [step, setStep] = useState(2);
  const labels = ru ? ["Заявка", "Принятие", "В работе", "Завершён"] : ["Request", "Acceptance", "In progress", "Completed"];
  const descriptions = ru ? ["Выберите площадку, рейтинг и формат игры. Заказ сохранится в вашем кабинете.", "После принятия заявки оплатите её и передайте данные в отдельной защищённой форме.", "Пишите в чат заказа и следите за статусом. Обновления публикует администратор.", "Проверьте результат с администратором. Условия и переписка останутся в вашем кабинете."] : ["Choose a platform, rating and playing method. Your order is saved in your account.", "After acceptance, pay and submit your details in the dedicated secure form.", "Use your order chat and follow its status. Updates are posted by the admin.", "Review the result with the admin. Your order terms and conversation remain in your account."];
  const features = [
    { icon: Crosshair, title: ru ? "Ваша цель" : "Your target", text: ru ? "Начальный и конечный рейтинг сохранены в заказе." : "Starting and target ratings are saved with your order." },
    { icon: ShieldCheck, title: ru ? "Зафиксированная цена" : "A saved price", text: ru ? "Сумма видна до оплаты. Новые условия требуют согласия." : "See the amount before paying. New terms require your agreement." },
    { icon: Timer, title: ru ? "Статус и срок" : "Status and timing", text: ru ? "Этап выполнения и таймер — рядом с условиями." : "Order stage and delivery timer beside your terms." },
    { icon: MessageSquare, title: ru ? "Прямой контакт" : "Direct contact", text: ru ? "Чат с администратором и отдельная поддержка." : "An admin conversation and separate support." },
  ];
  return <><section className="tactical-section process-section" id="process"><div className="wrap"><div className="section-heading"><div><span className="kicker">04 // MATCH PROGRESS</span><h2>{ru ? "От заявки до результата." : "From request to result."}</h2></div><span className="process-caption">{ru ? "ВЫБЕРИТЕ ЭТАП" : "EXPLORE EACH STAGE"}<ArrowRight size={15}/></span></div><ol className="process-rail" style={{ "--process-progress": `${step / 3}` } as CSSProperties}>{labels.map((label,index)=><li className={index === step ? "current" : index < step ? "done" : ""} key={label}><button type="button" aria-pressed={step === index} aria-controls="stage-description" onClick={()=>setStep(index)}><span className="process-node">{index < step ? <Check size={13}/> : <i/>}</span><small>0{index+1}</small><strong>{label}</strong><ArrowUpRight size={16}/></button></li>)}</ol><p className="stage-description" id="stage-description" aria-live="polite">{descriptions[step]}</p></div></section>
  <section className="tactical-section account-showcase"><div className="wrap showcase-grid"><div className="account-preview"><div className="preview-heading"><div><span className="signal-dot"/><strong>CS2 BOOST / WORKSPACE</strong></div><span>{ru ? "ПРИМЕР ИНТЕРФЕЙСА" : "INTERFACE PREVIEW"}</span></div><div className="preview-body"><div className="preview-order"><span>ORDER / DEMO</span><span className={`status status-${["new", "awaiting_payment", "in_progress", "completed"][step]}`}>{labels[step]}</span></div><div className="preview-title"><Crosshair size={23}/><h3>PREMIER <small>/ DUO</small></h3></div><div className="preview-rating"><div><small>{ru ? "НАЧАЛО" : "START"}</small><strong>4 500</strong></div><ArrowUpRight size={29}/><div><small>{ru ? "ЦЕЛЬ" : "TARGET"}</small><strong>10 000</strong></div><span className="preview-delta">+5 500</span></div><div className="preview-progress"><div style={{ width: `${(step+1)/4*100}%` }}/></div><div className="preview-terms"><div><span>{ru ? "СТОИМОСТЬ" : "PRICE"}</span><strong>{ru ? "2 750 ₽" : "2,750 RUB"}</strong></div><div><span>{ru ? "СРОК" : "DURATION"}</span><strong>{ru ? "6 дней" : "6 days"}</strong></div><div><span>{ru ? "ФОРМАТ" : "METHOD"}</span><strong>DUO</strong></div></div><div className="preview-chat"><div className="preview-avatar">A</div><div><strong>{ru ? "Администратор" : "Administrator"}<small>{ru ? "ЧАТ ЗАКАЗА" : "ORDER CHAT"}</small></strong><p>{step === 3 ? (ru ? "Цель достигнута. Проверьте результат в игре." : "Target reached. Please check the result in game.") : step === 2 ? (ru ? "Начали выполнение. Все обновления будут здесь." : "We've started. All updates will be posted here.") : step === 1 ? (ru ? "Заказ принят. Можем переходить к оплате." : "Order accepted. You can proceed to payment.") : (ru ? "Получили вашу заявку. Уточним детали в этом чате." : "We've received your request. Let's discuss the details here.")}</p></div><span className="preview-time">12:42</span></div><div className="preview-note"><LockKeyhole size={13}/>{ru ? "Данные аккаунта передаются в отдельной форме" : "Account details use a dedicated form"}</div></div></div><div className="showcase-copy"><span className="kicker">05 // CONTROL CENTER</span><h2>{ru ? "Всё под вашим контролем." : "Everything under your control."}</h2><p>{ru ? "Один заказ. Один кабинет. Все договорённости на месте." : "One order. One workspace. Every agreement in place."}</p><div className="showcase-features">{features.map(({icon: Icon,title,text},index)=><div key={title}><span className="feature-number">0{index+1}</span><Icon size={19}/><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><a className="service-text-link" href="/dashboard">{ru ? "Открыть кабинет" : "Open your account"}<ArrowUpRight size={16}/></a></div></div></section></>;
}
