import { ArrowRight, ArrowUpRight, FileText, Mail, ShieldCheck } from "lucide-react";
import type { Language } from "@/lib/marketing";
import { legalDate, legalDetails, legalLabels, legalSlugs, type LegalSlug } from "@/lib/legal-config";
import { legalContent } from "@/lib/legal-content";
import { MarketingFooter, MarketingHeader } from "./marketing-ui";

export function LegalFrame({ lang, slug, children }: { lang: Language; slug?: LegalSlug; children: React.ReactNode }) {
  return <div className="site legal-page"><MarketingHeader lang={lang} slug={`legal${slug ? `/${slug}` : ""}`} showMobileCta={false}/><main className="wrap legal-main">{children}</main><MarketingFooter lang={lang} compact/></div>;
}

export function LegalNotice({ lang }: { lang: Language }) {
  if (legalDetails.status !== "draft") return null;
  const ru = lang === "ru";
  return <aside className="legal-notice"><FileText size={20}/><div><strong>{ru ? "Проекты документов" : "Draft documents"}</strong><p>{ru ? "Полные сведения о владельце, размещении базы и сроках хранения ещё не утверждены. Эта редакция предназначена для ознакомления и согласования; она не объявляется публичной офертой." : "Full owner details, database location and retention periods have not been approved. This edition is for review and agreement, and is not presented as a public offer."}</p></div><span>{ru ? "НА СОГЛАСОВАНИИ" : "FOR REVIEW"}</span></aside>;
}

export function LegalOwner({ lang }: { lang: Language }) {
  const ru = lang === "ru";
  const missing = ru ? "Не заполнено" : "Not supplied";
  return <section className="legal-owner" id="owner"><div className="legal-owner-heading"><ShieldCheck size={21}/><h2>{ru ? "Владелец и обращения" : "Owner and enquiries"}</h2></div><dl><div><dt>{ru ? "Статус" : "Capacity"}</dt><dd>{ru ? "Физическое лицо" : "Individual"}</dd></div><div><dt>{ru ? "Страна владельца" : "Owner's country"}</dt><dd>{legalDetails.operatorCountry[lang]}</dd></div><div><dt>{ru ? "ФИО владельца" : "Owner's full name"}</dt><dd className={!legalDetails.operatorName ? "legal-missing" : undefined}>{legalDetails.operatorName || missing}</dd></div><div><dt>{ru ? "Контактный адрес" : "Contact address"}</dt><dd className={!legalDetails.operatorAddress ? "legal-missing" : undefined}>{legalDetails.operatorAddress || missing}</dd></div><div><dt>{ru ? "Страна размещения базы" : "Database hosting country"}</dt><dd className={!legalDetails.hostingCountry ? "legal-missing" : undefined}>{legalDetails.hostingCountry || missing}</dd></div><div><dt>Email</dt><dd><a href={`mailto:${legalDetails.email}`}>{legalDetails.email}</a></dd></div></dl><div className="legal-contact"><div><strong>{ru ? "Заказ, возврат или запрос по данным" : "Order, refund or data request"}</strong><p>{ru ? "Укажите номер заказа и суть вопроса. Пароли и коды доступа не прикладывайте." : "Include your order number and the issue. Do not attach passwords or access codes."}</p></div><a href={`mailto:${legalDetails.email}`}><Mail size={17}/>{ru ? "Написать владельцу" : "Email the owner"}<ArrowUpRight size={16}/></a></div></section>;
}

export function LegalIndex({ lang }: { lang: Language }) {
  const ru = lang === "ru";
  return <LegalFrame lang={lang}><header className="legal-heading"><span className="kicker">CS2 BOOST / DOCUMENTS</span><h1>{ru ? "Документы сервиса" : "Service documents"}</h1><p>{ru ? "Порядок заказа, оплаты, работы с данными и хранения настроек — в одном месте." : "Order terms, payments, information handling and browser settings, in one place."}</p><span className="legal-version">{ru ? "Редакция" : "Edition"} / {legalDate(lang)}</span></header><LegalNotice lang={lang}/><div className="legal-cards">{legalSlugs.map((slug, index) => <a className="legal-card" key={slug} href={`/${lang}/legal/${slug}`}><div className="legal-card-top"><span>0{index + 1}</span><FileText size={21}/></div><h2>{legalLabels[lang][slug]}</h2><p>{legalContent[lang][slug].description}</p><span className="legal-card-link">{ru ? "Читать документ" : "Read document"}<ArrowRight size={17}/></span></a>)}</div><LegalOwner lang={lang}/></LegalFrame>;
}

export function LegalArticle({ lang, slug }: { lang: Language; slug: LegalSlug }) {
  const ru = lang === "ru";
  const content = legalContent[lang][slug];
  return <LegalFrame lang={lang} slug={slug}><nav className="legal-breadcrumbs" aria-label={ru ? "Путь страницы" : "Breadcrumb"}><a href={`/${lang}`}>{ru ? "Главная" : "Home"}</a><span>/</span><a href={`/${lang}/legal`}>{ru ? "Документы" : "Documents"}</a></nav><header className="legal-heading"><span className="kicker">LEGAL / 0{legalSlugs.indexOf(slug) + 1}</span><h1>{legalLabels[lang][slug]}</h1><p>{content.description}</p><span className="legal-version">{ru ? "Редакция" : "Edition"} / {legalDate(lang)}</span></header><LegalNotice lang={lang}/><div className="legal-highlights">{content.summary.map((line, index) => <div key={line}><span>0{index + 1}</span><p>{line}</p></div>)}</div><div className="legal-reader"><aside className="legal-sidebar"><details className="legal-toc" open><summary>{ru ? "Содержание" : "Contents"}</summary><ol>{content.sections.map((section, index) => <li key={section.id}><a href={`#section-${section.id}`}><span>{String(index + 1).padStart(2, "0")}</span>{section.title}</a></li>)}<li><a href="#owner"><span>↗</span>{ru ? "Владелец и обращения" : "Owner and enquiries"}</a></li></ol></details><nav className="legal-other" aria-label={ru ? "Другие документы" : "Other documents"}><h2>{ru ? "Другие документы" : "Other documents"}</h2>{legalSlugs.filter(other => other !== slug).map(other => <a key={other} href={`/${lang}/legal/${other}`}>{legalLabels[lang][other]}<ArrowUpRight size={14}/></a>)}</nav></aside><article className="legal-text">{content.sections.map((section, index) => <section key={section.id} id={`section-${section.id}`}><h2><span>{String(index + 1).padStart(2, "0")}</span>{section.title}</h2>{section.paragraphs?.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.list && <ul>{section.list.map(item => <li key={item}>{item}</li>)}</ul>}{section.table && <div className="legal-table-wrap" role="region" aria-label={section.title} tabIndex={0}><table><thead><tr>{section.table.headings.map(heading => <th key={heading} scope="col">{heading}</th>)}</tr></thead><tbody>{section.table.rows.map(row => <tr key={row[0]}>{row.map((cell, cellIndex) => cellIndex === 0 ? <th key={cellIndex} scope="row">{cell}</th> : <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>}{section.links && <nav className="legal-related" aria-label={ru ? "Связанные документы" : "Related documents"}>{section.links.map(link => <a key={link.href} href={link.href.startsWith("https:") ? link.href : `/${lang}/legal/${link.href}`} rel={link.href.startsWith("https:") ? "noopener noreferrer" : undefined}>{link.label}<ArrowUpRight size={14}/></a>)}</nav>}</section>)}<LegalOwner lang={lang}/></article></div></LegalFrame>;
}
