import type { Language } from "./marketing";
import type { LegalSlug } from "./legal-config";

export type LegalSection = {
  id: string;
  title: string;
  paragraphs?: string[];
  list?: string[];
  table?: { headings: string[]; rows: string[][] };
  links?: { label: string; href: string }[];
};
export type LegalDocument = { description: string; summary: string[]; sections: LegalSection[] };

export const legalContent: Record<Language, Record<LegalSlug, LegalDocument>> = {
  ru: {
    terms: {
      description: "Как пользоваться CS2 Boost, оформлять заказы и согласовывать выполнение услуг в Premier и FACEIT.",
      summary: ["Условия видны до оплаты", "Заказ и переписка в кабинете", "Правила площадок продолжают действовать"],
      sections: [
        { id: "service", title: "Сервис и стороны", paragraphs: ["CS2 Boost на cs2-boosts.ru — независимый сервис оформления и сопровождения заказов на повышение рейтинга и калибровку в CS2 Premier и FACEIT. Владелец сервиса действует как физическое лицо в Казахстане. Сведения о владельце и контакт для обращений приведены в конце документа.", "Сервис не является подразделением, партнёром или представителем Valve, Steam либо FACEIT. Названия игр и площадок используются для описания услуг; права на них принадлежат соответствующим правообладателям.", "Эта редакция является проектом пользовательского соглашения. Она не объявляется публичной офертой: полные сведения об исполнителе и окончательные юридические условия ещё не утверждены. Конкретный объём услуги, цена, способ выполнения и срок фиксируются в заказе до оплаты."] },
        { id: "account", title: "Аккаунт и право на заказ", paragraphs: ["Указывайте действующий email и подтверждайте его через письмо. Используйте игровой аккаунт, которым вправе распоряжаться, и предоставляйте достоверные сведения о рейтинге, ограничениях, регионе и доступном времени.", "Оформлять платный заказ можно при наличии необходимой дееспособности и права заключать договор. Если требуется участие законного представителя, согласуйте это до оплаты. Не заказывайте доступ к чужим аккаунтам без разрешения их владельца.", "Сохраняйте пароль сайта и резервные коды двухфакторной защиты в тайне. При подозрении на чужой вход смените пароль, завершите активные входы и свяжитесь с администратором. Не сообщайте банковские пароли, SMS-коды или платёжные реквизиты в чате."] },
        { id: "order", title: "Оформление и согласование заказа", list: ["В калькуляторе выберите площадку, услугу, способ выполнения и, для буста рейтинга, начальное и целевое значения.", "Цена буста и расчётный срок сохраняются при оформлении. Условия калибровки предлагаются отдельно и подтверждаются клиентом.", "Администратор проверяет возможность выполнения и принимает заявку либо предлагает изменения. Поданная заявка сама по себе не означает принятия и не требует оплаты.", "Новое предложение по цене и длительности до оплаты требует подтверждения клиента. После подтверждения оплаты стоимость заказа нельзя изменить односторонне.", "Оплачивайте только принятую заявку по реквизитам, согласованным в её чате. Автоматическое списание и подписка не используются."] },
        { id: "methods", title: "DUO и PILOTED", paragraphs: ["В DUO вы играете на своём аккаунте вместе с исполнителем. Согласуйте профиль, регион и расписание. Пароль игрового аккаунта для этого формата не требуется.", "В PILOTED исполнитель играет на аккаунте по согласованным условиям. После подтверждения оплаты используйте отдельную форму доступа внутри заказа. Не передавайте пароль Steam или коды Steam Guard через обычный чат. Подтверждение входа согласуйте при необходимости; не отключайте защиту аккаунта по случайным сообщениям.", "Способ выполнения сохраняется при создании заказа. Для его изменения обратитесь к администратору до начала матчей: может понадобиться отмена прежней заявки и оформление новой. По окончании доступа смените пароль игрового аккаунта и проверьте активные входы."] },
        { id: "delivery", title: "Результат и срок", paragraphs: ["Для буста согласованный результат — достижение целевого рейтинга в заказе; для калибровки результат и объём матчей согласуются отдельно. Дальнейшее сохранение рейтинга после выполнения не обещается.", "Стандартный расчёт — один день на 1 000 рейтинга Premier либо 100 ELO FACEIT с округлением вверх. Таймер начинается после подтверждения оплаты и передачи необходимых данных или расписания DUO. Проверяйте согласованную длительность и дату в карточке заказа.", "Статусы и сообщения обновляет администратор. Автоматического отслеживания игровых матчей нет. Если возникают задержки, обсудите причину и дальнейшие действия в чате. Новый срок фиксируется в истории; бонусы согласуются отдельно. Перенос срока не отменяет права клиента в связи с просрочкой."] },
        { id: "risks", title: "Правила площадок и ответственность", paragraphs: ["Буст, совместная игра ради повышения рейтинга и передача аккаунта могут нарушать правила Steam, CS2 и FACEIT. Возможны снижение рейтинга, отмена результата, ограничения доступа или блокировка. Ни DUO, ни PILOTED не гарантируют отсутствие санкций.", "Ознакомьтесь с действующими правилами выбранной площадки до заказа. Подтверждение риска на сайте не изменяет эти правила и не означает согласия площадки на услугу. Сервис не принимает решения о санкциях и не может обещать их отмену.", "Владелец отвечает за собственные действия и исполнение согласованных обязательств в пределах применимого закона. Этот документ и отметка о рисках не исключают ответственность за виновное нарушение, недобросовестные действия и обязательные права потребителя. Запрещены попытки взлома сайта, выдача себя за другого пользователя и передача незаконно полученных данных."] },
        { id: "disputes", title: "Отмена, обращения и изменения", paragraphs: ["Порядок отмены и возвратов описан в отдельном документе. По вопросам заказа используйте его чат; по другим вопросам — поддержку или публичный email владельца. Укажите номер заказа и суть обращения, не прикладывайте пароли и коды доступа.", "Сначала стороны выясняют обстоятельства и обсуждают решение. Возможность обращения в суд, к уполномоченным органам и использования иных предусмотренных законом способов защиты сохраняется. Обязательные нормы применимого законодательства имеют приоритет над противоречащими им положениями документа.", "Новая редакция публикуется с датой. Изменения не дают права задним числом ухудшать согласованные условия оплаченного заказа. Английский перевод предоставляется для удобства; если обнаружена неоднозначность, стороны уточняют условия, сохраняя обязательные права клиента."], links: [{ label: "Оплата, отмена и возвраты", href: "payments" }, { label: "Политика конфиденциальности", href: "privacy" }] },
      ],
    },
    privacy: {
      description: "Какие данные нужны CS2 Boost для регистрации, заказов, переписки и защиты аккаунта, кому они доступны и как направить запрос.",
      summary: ["Пароль сайта хранится как хеш", "Игровой доступ передаётся отдельно", "Запросы по данным — на email владельца"],
      sections: [
        { id: "operator", title: "Оператор и область политики", paragraphs: ["Оператором данных является физическое лицо — владелец CS2 Boost в Казахстане. Email для обращений указан в конце документа. Эта политика описывает текущую работу cs2-boosts.ru и не регулирует самостоятельные сервисы Steam, FACEIT, почтового провайдера или вашего банка.", "Редакция является проектом. До утверждения необходимо заполнить полные сведения об операторе, местонахождении базы данных и сроки хранения, а также согласовать необходимые основания обработки и форму согласия. Размещение политики само по себе не заменяет получение согласия там, где оно требуется."] },
        { id: "data", title: "Какие данные обрабатываются", table: { headings: ["Категория", "Состав и назначение"], rows: [["Регистрация и вход", "Email, дата регистрации и подтверждения адреса, хеш пароля сайта, данные сессий и попыток входа. Нужны для доступа и защиты аккаунта."], ["Двухфакторная защита", "Зашифрованный секрет приложения, хеши резервных кодов и сведения о проверке кода, если вы подключаете защиту."], ["Заказ и оплата", "Площадка, услуга, способ игры, рейтинг, красный траст, промокод, сумма, сроки, статусы и факт подтверждения оплаты администратором."], ["Связь и выполнение", "Сообщения в чатах заказа и поддержки, игровой профиль, расписание и согласованные сведения для выполнения."], ["Доступ PILOTED", "Логин и пароль игрового аккаунта из отдельной формы; запись хранится в зашифрованном виде. Для DUO вместо пароля нужны профиль и время игры."], ["Технические сведения", "IP-адрес, адрес запрошенной страницы, время обращения и сведения браузера могут попадать в журналы веб-сервера. Ограничение попыток использует хешированные технические ключи."], ["Источник заявки", "UTM-параметры ссылки и использованный промокод, если они переданы при оформлении. Используются для внутренней статистики источников заказов."]] } },
        { id: "purposes", title: "Для чего нужны данные", list: ["Подтвердить email, обеспечить вход и защитить аккаунт от чужого доступа.", "Рассчитать и согласовать услугу, организовать выполнение, показать статус, срок и историю заказа.", "Вести переписку с клиентом, рассматривать вопросы оплаты, отмены, возврата и претензии.", "Поддерживать работу сервера, выявлять злоупотребления и восстанавливать сервис из резервных копий.", "Оценивать источники заявок по параметрам переданной ссылки; не создавать профиль посещений на сторонних сайтах."], paragraphs: ["Для обработки используются необходимые и допускаемые законом основания: выполнение согласованных обязательств, обязательные требования закона и отдельное согласие в случаях, когда оно требуется. Рекламная рассылка не включена в согласование заказа; сейчас сайт отправляет письма для подтверждения регистрации."] },
        { id: "recipients", title: "Кому доступны сведения", paragraphs: ["Данные доступны владельцу и администраторам в пределах их работы с заказами и поддержкой. Исполнителю предоставляются только согласованные сведения, необходимые для конкретной услуги. Игровой пароль не нужен для DUO.", "Письма регистрации отправляются через Resend (Plus Five Five, Inc.). Провайдер получает адрес получателя и содержимое письма, включая ссылку подтверждения. Пароль сайта и игровой пароль в эти письма не добавляются. По политике Resend обработка данных может происходить в США.", "Хостинг-провайдер обслуживает инфраструктуру сайта; сведения о стране размещения базы ещё необходимо уточнить. Само использование зарубежной почты не подтверждает соблюдение требований к локализации и трансграничной передаче данных. Эти условия должны быть проверены перед утверждением политики.", "Сайт не принимает номер банковской карты, CVC/CVV или банковские SMS-коды. При ручной оплате данные обрабатывает ваш банк и получатель платежа. При подключении платёжного провайдера его сведения и порядок обработки будут добавлены в политику. Передача уполномоченным органам возможна в предусмотренных законом случаях."], links: [{ label: "Политика конфиденциальности Resend", href: "https://resend.com/legal/privacy-policy" }] },
        { id: "retention", title: "Хранение и удаление", paragraphs: ["Ссылка регистрации действует 30 минут. После успешной регистрации связанные записи подтверждения удаляются; просроченные записи очищаются при следующих запросах регистрации. Обычная сессия действует до семи дней, промежуточная проверка двухфакторного входа — до пяти минут.", "Доступ к записи с данными игрового аккаунта истекает не позднее 30 дней после её передачи, обычно раньше — в зависимости от срока заказа. Активная запись удаляется при завершении заказа или фиксации возврата; истёкшие записи очищаются при операциях с доступом и резервном копировании. После окончания работы рекомендуем сменить игровой пароль.", "Завершение заказа не удаляет автоматически его историю, переписку и аккаунт клиента. Для исправления или удаления направьте запрос владельцу. Сведения, необходимые для действующего заказа, законных обязанностей или разрешения спора, могут сохраняться при наличии законного основания; об этом сообщается в ответе.", "Штатное резервное копирование сохраняет последние 14 копий базы. Удалённые сведения могут оставаться в ранее созданных копиях до их ротации; это не равнозначно 14 календарным дням. Перед утверждением политики владелец должен установить сроки хранения истории, журналов и порядок удаления из резервных копий."] },
        { id: "security", title: "Защита данных", paragraphs: ["На опубликованном сайте используется HTTPS. Пароль сайта хранится как хеш, а секрет двухфакторной защиты и данные отдельной формы игрового доступа — в зашифрованном виде. Сервер проверяет права доступа к заказам и переписке. Эти меры снижают риск, но не дают обещания абсолютной безопасности.", "Чат предназначен для обсуждения заказа. Не размещайте в нём пароли, коды Steam Guard, резервные коды, банковские данные или документы, которые не нужны для решения вопроса. Не используйте общий компьютер для передачи доступа, если не можете защитить свои данные."] },
        { id: "rights", title: "Как обратиться по своим данным", paragraphs: ["Напишите на публичный email владельца с адреса, связанного с аккаунтом, либо создайте обращение в поддержке. Можно запросить информацию об обработке, исправление неточных данных, удаление или ограничение обработки, а также отозвать согласие в предусмотренных законом случаях.", "Для проверки принадлежности аккаунта может потребоваться подтверждение адреса или сведений о заказе. Не отправляйте паспорт, пароль или резервные коды без отдельного объяснения необходимости и безопасного способа передачи. Если без необходимых данных продолжить услугу нельзя, владелец объяснит последствия и предложит обсудить завершение заказа.", "Ответ и действия выполняются в сроки применимого законодательства. Возможность обращения в уполномоченный орган или суд сохраняется. Изменения политики публикуются с датой редакции; новые цели обработки и получатели должны быть раскрыты до начала соответствующей обработки."], links: [{ label: "Cookies и хранение в браузере", href: "cookies" }] },
      ],
    },
    payments: {
      description: "Когда оплачивать заказ CS2 Boost, как подтверждается платёж и как обратиться за отменой или возвратом.",
      summary: ["Оплата после принятия заявки", "Получение подтверждает администратор", "Возврат рассматривается по обстоятельствам заказа"],
      sections: [
        { id: "price", title: "Цена и согласованные условия", paragraphs: ["Цена буста рассчитывается в рублях и сохраняется при оформлении. Для Premier базовый тариф — 500 ₽ за 1 000 рейтинга; при исходном рейтинге выше 10 000 — 700 ₽. Для FACEIT — 500 ₽ за 100 ELO; при исходном ELO выше 1 200 — 700 ₽. Тариф определяется исходным рейтингом и применяется ко всему заказу, а неполный шаг оплачивается пропорционально.", "Красный траст в Premier увеличивает базовую стоимость на 10%. Действующий промокод Cherep или Terasay уменьшает сумму после надбавки на 20%. Проверяйте конечную сумму в заказе. Промокод даёт скидку на услугу и не является обещанием выплаты клиенту.", "Для калибровки цена и длительность предлагаются отдельно. Иные обстоятельства обсуждаются до оплаты; изменённое предложение требует вашего подтверждения. Оплаченный заказ не получает одностороннюю надбавку задним числом."] },
        { id: "payment", title: "Порядок оплаты", list: ["Отправьте заявку и дождитесь её принятия администратором.", "Проверьте сумму, длительность и формат игры в карточке заказа.", "Получите реквизиты в чате конкретного заказа. Если платёж будет в другой валюте, до перевода согласуйте сумму и порядок конвертации; банк может применять свои комиссии.", "Переведите согласованную сумму. При необходимости сообщите дату и сумму платежа; скрывайте лишние персональные сведения в подтверждении.", "Дождитесь отметки о получении оплаты от администратора. Платёжный скриншот сам по себе не подтверждает зачисление.", "Передайте данные через отдельную форму или согласуйте расписание DUO. После этого запускается срок выполнения."], paragraphs: ["Автоматическая платёжная система пока не подключена: сайт не списывает деньги с карты, не хранит её реквизиты и не оформляет подписку. Не переводите деньги по сообщениям вне согласованного чата, если не проверили получателя."] },
        { id: "cancel", title: "Отмена до начала выполнения", paragraphs: ["До подтверждения оплаты заявку можно отменить в кабинете с указанием причины. Если деньги уже переведены, но отметки ещё нет, сообщите об этом администратору и запросите сверку: отмена заявки не возвращает банковский перевод автоматически.", "После оплаты направьте запрос об отмене в чат или на публичный email. Если выполнение не начиналось и подтверждённых расходов по заказу нет, предлагается полный возврат. При наличии допустимых по закону фактических расходов предоставляется их обоснование и расчёт суммы. Фиксированный штраф за отмену не устанавливается."] },
        { id: "partial", title: "Начатая услуга, задержка и претензия", paragraphs: ["Отказ от продолжения уже начатого заказа рассматривается с учётом выполненного объёма, подтверждённых расходов и обязательных прав клиента. Сумма возврата определяется по обстоятельствам; по запросу предоставляется расчёт. Нельзя считать всю оплату невозвратной только потому, что работа уже началась.", "При просрочке или невозможности выполнения сообщите, хотите ли вы обсудить продолжение, новый срок либо прекращение услуги. Причина и дальнейшие договорённости фиксируются в чате и истории заказа. Бонус не заменяет возврат или другое средство защиты, если оно положено по закону.", "Если услуга выполнена с недостатками или не соответствует согласованному результату, опишите проблему и приложите необходимые подтверждения без паролей. Ограничения площадки оцениваются по конкретным обстоятельствам; ознакомление с рисками не исключает ответственность исполнителя за собственные нарушения."] },
        { id: "refund", title: "Как оформляется возврат", paragraphs: ["Укажите номер заказа, email аккаунта, дату и сумму оплаты, причину обращения и желаемое решение. Используйте чат заказа либо контакт владельца в конце документа. Для возврата может понадобиться безопасно согласовать реквизиты первоначального плательщика; пароль банка, CVC/CVV и SMS-коды не требуются.", "Сейчас возврат выполняется вручную банковским переводом, а не автоматически через сайт. Администратор сообщает решение, расчёт и сведения об отправке средств. По возможности возврат направляется первоначальному плательщику тем же способом. Срок зачисления зависит от банка; обязательные сроки и требования закона сохраняют приоритет.", "Отметка о возврате в кабинете является записью об операции, а не самостоятельным движением денег. Если средства не поступили, обратитесь за проверкой. Двойная оплата, ошибка суммы или спор о зачислении также рассматриваются по фактическим платежам."] },
        { id: "rights", title: "Права клиента и статус документа", paragraphs: ["Это проект правил оплаты, отмены и возвратов. Он не ограничивает права клиента, которые нельзя исключить соглашением, и не заменяет утверждённый договор с идентифицированным исполнителем. При противоречии обязательные нормы закона имеют приоритет.", "Новые условия не применяются задним числом для ухудшения условий уже оплаченного заказа. Вопросы сначала обсуждаются с владельцем; право обращения в уполномоченный орган и суд сохраняется."], links: [{ label: "Пользовательское соглашение", href: "terms" }] },
      ],
    },
    cookies: {
      description: "Какие cookies и записи браузера использует CS2 Boost и как управлять сохранёнными настройками и черновиками.",
      summary: ["Cookies нужны для входа", "Черновики сохраняются в текущей вкладке", "Сторонние рекламные пиксели не подключены"],
      sections: [
        { id: "types", title: "Cookies и локальное хранение", paragraphs: ["Cookies передаются браузером серверу и помогают поддерживать вход. localStorage хранит настройки в браузере между посещениями; sessionStorage хранит данные текущей вкладки. Удаление этих записей влияет на удобство использования, но не удаляет аккаунт или историю заказов в базе.", "Это описание текущей реализации. Редакция является проектом и должна быть согласована вместе с политикой конфиденциальности и необходимыми настройками согласия."] },
        { id: "inventory", title: "Что сохраняется", table: { headings: ["Запись", "Назначение", "Срок"], rows: [["__Host-cs2_session", "Cookie входа. HttpOnly, Secure и SameSite=Lax на HTTPS. Содержит случайный идентификатор сессии.", "До 7 дней; прекращается при выходе или отзыве входов."], ["__Host-cs2_mfa", "Промежуточная cookie для подтверждения входа с двухфакторной защитой.", "До 5 минут."], ["cs2-lang · localStorage", "Выбранный язык интерфейса.", "До изменения или очистки браузером."], ["cs2-draft, cs2-promo · sessionStorage", "Параметры заявки и выбранный промокод, чтобы сохранить настройку между шагами.", "На время вкладки; черновик заказа удаляется после отправки."], ["Черновики сообщений · sessionStorage", "Неотправленный текст в чате заказа или поддержки.", "На время вкладки либо до очистки черновика."], ["cs2-campaign · sessionStorage", "UTM-источник, канал, кампания и вариант ссылки для статистики заявок.", "На время вкладки; при оформлении сведения могут сохраняться с заказом."]] }, paragraphs: ["В локальном просмотре по HTTP cookies входа называются cs2_session и cs2_mfa. Это не означает, что опубликованный сайт следует использовать без HTTPS."] },
        { id: "tracking", title: "Статистика и сторонние сервисы", paragraphs: ["Google Analytics, Яндекс Метрика и сторонние рекламные пиксели в текущую версию не встроены. Внутренняя статистика источников использует параметры рекламной ссылки, сохранённые вместе с заявкой. Отсутствие сторонних пикселей не означает, что сайт совсем не обрабатывает технические сведения.", "Если будут подключаться дополнительные системы аналитики, рекламное отслеживание или иные необязательные технологии, их состав и срок хранения должны быть раскрыты заранее. Там, где требуется согласие, их включение должно зависеть от отдельного выбора, а не только от просмотра этой страницы."] },
        { id: "control", title: "Как управлять данными браузера", list: ["В настройках браузера найдите данные сайта cs2-boosts.ru: можно удалить cookies и локальное хранилище именно для этого сайта.", "Удаление cookie входа завершит сеанс в этом браузере. Для завершения входов на других устройствах используйте настройки аккаунта.", "Очистка localStorage сбросит выбранный язык. Очистка sessionStorage удалит сохранённые параметры заявки, промокод и неотправленные сообщения этой вкладки.", "Если полностью запретить cookies, вход и работа личного кабинета могут быть недоступны. Просматривать общую информацию и документы можно без аккаунта.", "Для удаления серверных данных направьте отдельный запрос владельцу: очистка браузера сама по себе не удаляет историю заказов."], links: [{ label: "Политика конфиденциальности", href: "privacy" }] },
      ],
    },
  },
  en: {
    terms: {
      description: "How to use CS2 Boost, place orders and agree on Premier and FACEIT services before payment.",
      summary: ["Terms before payment", "Orders and conversations in your account", "Platform rules still apply"],
      sections: [
        { id: "service", title: "The service and the parties", paragraphs: ["CS2 Boost at cs2-boosts.ru is an independent service for arranging and managing CS2 Premier and FACEIT rating boost and calibration orders. The owner operates as an individual in Kazakhstan. Owner details and the contact for enquiries appear at the end of this document.", "The service is not a division, partner or representative of Valve, Steam or FACEIT. Game and platform names describe the services; their rights belong to the respective owners.", "This edition is a draft of the terms of use, not a public offer. Full provider details and final legal terms have not been approved. The scope, price, playing method and duration of a particular service are recorded in the order before payment."] },
        { id: "account", title: "Your account and authority to order", paragraphs: ["Provide a valid email address and confirm it through the registration email. Only use a game account you are authorised to manage. Give accurate information about the rating, restrictions, region and availability.", "A paid order requires legal capacity and authority to enter the agreement. If a legal representative must participate, agree on this before paying. Do not order access to another person's account without the owner's permission.", "Keep your website password and two-factor recovery codes private. If you suspect an unauthorised sign-in, change your password, revoke active sessions and contact the admin. Do not share banking passwords, SMS codes or payment credentials in chat."] },
        { id: "order", title: "Placing and agreeing on an order", list: ["Choose the platform, service and playing method in the calculator. For a rating boost, enter the current and target ratings.", "The rating boost price and estimated duration are saved when ordering. Calibration terms are offered separately and need your acceptance.", "The admin checks availability and accepts the request or proposes changes. A submitted request is not acceptance and does not require payment.", "A revised price and duration before payment require your approval. The price cannot be increased unilaterally after payment is confirmed.", "Pay only for an accepted request using details agreed in that order's chat. There is no automatic debit or subscription."] },
        { id: "methods", title: "DUO and PILOTED", paragraphs: ["With DUO, you play on your own account alongside the booster. Agree on the profile, region and schedule. This method does not require your game account password.", "With PILOTED, the booster plays on the account under agreed conditions. After payment confirmation, use the dedicated access form inside the order. Do not share Steam passwords or Steam Guard codes in ordinary chat. Coordinate sign-in confirmation when needed; do not disable account protection in response to unsolicited messages.", "The playing method is saved when ordering. Contact the admin before any matches if you want to change it: cancelling the old request and creating a new one may be necessary. After access ends, change your game account password and review active sign-ins."] },
        { id: "delivery", title: "Result and delivery time", paragraphs: ["For rating boosts, the agreed result is the target rating in the order. Calibration results and match scope are agreed separately. Maintaining the rating after delivery is not promised.", "The standard estimate is one day per 1,000 Premier rating or 100 FACEIT ELO, rounded up. The timer starts after payment confirmation and submission of the required details or DUO schedule. Check the agreed duration and date in your order.", "The admin updates statuses and messages; matches are not tracked automatically. If delivery is delayed, discuss the reason and next steps in chat. A new deadline is recorded in the history; bonuses are agreed separately. Extending a deadline does not remove your rights concerning the delay."] },
        { id: "risks", title: "Platform rules and responsibility", paragraphs: ["Boosting, playing together to increase a rating and account sharing may violate Steam, CS2 and FACEIT rules. Possible consequences include rating reductions, reversal of results, account restrictions or bans. Neither DUO nor PILOTED guarantees freedom from sanctions.", "Review the platform's current rules before ordering. Acknowledging risks on this site does not change those rules or mean that the platform approves the service. The service does not decide sanctions and cannot promise to reverse them.", "The owner remains responsible for their own actions and agreed obligations under applicable law. This document and the risk acknowledgement do not exclude responsibility for culpable breaches or bad-faith conduct, or waive mandatory consumer rights. Attacks on the website, impersonation and providing unlawfully obtained data are prohibited."] },
        { id: "disputes", title: "Cancellation, enquiries and changes", paragraphs: ["Cancellation and refund procedures are described separately. Use the order chat for order matters, and support or the owner's public email for other enquiries. Include the order number and the issue, without passwords or access codes.", "The parties first review the circumstances and discuss a resolution. Your right to contact courts, competent authorities and use other legal remedies remains. Mandatory applicable law prevails over conflicting provisions in this document.", "New editions are published with a date. Changes do not permit retroactive worsening of the agreed terms of a paid order. This English translation is provided for convenience; ambiguities should be clarified while preserving mandatory customer rights."], links: [{ label: "Payments, cancellations & refunds", href: "payments" }, { label: "Privacy policy", href: "privacy" }] },
      ],
    },
    privacy: {
      description: "What information CS2 Boost uses for registration, orders, communication and account protection, who receives it and how to make a request.",
      summary: ["Website passwords are hashed", "Game access has a dedicated form", "Data enquiries go to the owner's email"],
      sections: [
        { id: "operator", title: "The operator and scope", paragraphs: ["The data operator is an individual: the owner of CS2 Boost in Kazakhstan. The contact email appears at the end of this document. This policy describes cs2-boosts.ru and does not govern independent Steam, FACEIT, email provider or banking services.", "This edition is a draft. Full operator details, database location and retention periods must be completed, and the required processing grounds and consent mechanism agreed before approval. Publishing a policy does not itself obtain consent where it is required."] },
        { id: "data", title: "Information processed", table: { headings: ["Category", "Details and purpose"], rows: [["Registration and sign-in", "Email, registration and confirmation dates, website password hash, sessions and sign-in attempts. Used for account access and protection."], ["Two-factor protection", "An encrypted authenticator secret, hashed recovery codes and code verification records if you enable this feature."], ["Orders and payment", "Platform, service, playing method, rating, red trust, promo code, amount, deadlines, statuses and the admin's payment confirmation."], ["Communication and delivery", "Order and support messages, game profile, schedule and agreed details needed for delivery."], ["PILOTED access", "Game login and password from the dedicated form, stored as an encrypted record. DUO uses a profile and schedule instead of a password."], ["Technical information", "IP address, requested page, time and browser information may appear in web server logs. Attempt limits use hashed technical keys."], ["Request source", "Link UTM parameters and the applied promo code if provided when ordering. Used for internal order source statistics."]] } },
        { id: "purposes", title: "Why information is needed", list: ["Confirm email, provide sign-in and protect accounts against unauthorised access.", "Calculate and agree on a service, arrange delivery, and display status, duration and order history.", "Communicate with clients and handle payment, cancellation, refund and complaint matters.", "Maintain the server, detect abuse and recover the service from backups.", "Evaluate request sources using parameters of the provided link, without building a cross-site browsing profile."], paragraphs: ["Processing must use necessary, legally permitted grounds: agreed obligations, legal requirements and separate consent where required. Agreement on an order does not include marketing email subscriptions; the current site sends registration confirmation emails."] },
        { id: "recipients", title: "Who receives information", paragraphs: ["The owner and admins access information needed for orders and support. A booster receives only agreed details necessary for the particular service. DUO does not require a game password.", "Registration emails use Resend (Plus Five Five, Inc.). The provider receives the recipient's address and email content, including the confirmation link. Website and game passwords are not included. Resend's policy states that data may be processed in the United States.", "The hosting provider maintains the website infrastructure; the database hosting country still needs confirmation. Using a foreign email provider does not establish compliance with localisation and international transfer requirements. These arrangements must be reviewed before policy approval.", "The site does not collect card numbers, CVC/CVV or banking SMS codes. For manual payments, your bank and the recipient process payment information. A future payment provider and its processing arrangements will be added to the policy. Information may be disclosed to competent authorities where required by law."], links: [{ label: "Resend privacy policy", href: "https://resend.com/legal/privacy-policy" }] },
        { id: "retention", title: "Retention and deletion", paragraphs: ["Registration links expire after 30 minutes. Related verification records are deleted after successful registration; expired records are cleaned up during subsequent registration requests. Ordinary sign-in sessions last up to seven days; an intermediate two-factor challenge lasts up to five minutes.", "Access to a game access record expires no later than 30 days after submission, usually sooner depending on the order deadline. The active record is deleted on completion or recorded refund; expired records are cleaned up during access operations and backups. Change your game password after delivery.", "Completing an order does not automatically delete its history, conversations or the client account. Send a correction or deletion request to the owner. Information needed for an active order, legal duties or a dispute may be retained on a lawful basis, which will be explained in the response.", "The standard backup process retains the latest 14 database copies. Deleted information may remain in existing backups until rotation; this does not mean 14 calendar days. Before policy approval, the owner must define history and log retention periods and the backup deletion procedure."] },
        { id: "security", title: "Information protection", paragraphs: ["The published site uses HTTPS. Website passwords are hashed; authenticator secrets and dedicated game access records are encrypted. The server checks permissions for orders and conversations. These measures reduce risks but do not promise absolute security.", "Use chat to discuss orders. Do not post passwords, Steam Guard codes, recovery codes, banking information or documents unnecessary for the enquiry. Avoid submitting account access from a shared computer if you cannot protect your information."] },
        { id: "rights", title: "Making a data request", paragraphs: ["Email the owner from the address associated with your account, or contact support. You can request information about processing, correction, deletion or restriction, and withdraw consent where applicable law permits.", "Account ownership may need confirmation through your email address or order details. Do not send identity documents, passwords or recovery codes without an explanation of necessity and a secure submission method. If a service cannot continue without required information, the owner will explain the consequences and discuss how to end the order.", "Responses and actions follow applicable statutory timelines. You retain the right to complain to a competent authority or court. Policy changes carry a date; new purposes and recipients must be disclosed before the relevant processing starts."], links: [{ label: "Cookies & browser storage", href: "cookies" }] },
      ],
    },
    payments: {
      description: "When to pay for a CS2 Boost order, how payment is confirmed and how to request cancellation or a refund.",
      summary: ["Payment after acceptance", "Receipt confirmed by the admin", "Refunds depend on the order circumstances"],
      sections: [
        { id: "price", title: "Price and agreed terms", paragraphs: ["Rating boost prices are calculated in RUB and saved when ordering. Premier costs 500 RUB per 1,000 rating, or 700 RUB if the starting rating is above 10,000. FACEIT costs 500 RUB per 100 ELO, or 700 RUB if starting ELO is above 1,200. The starting tier applies to the whole order; partial steps are priced proportionally.", "Premier red trust increases the base price by 10%. A valid Cherep or Terasay promo code discounts the amount after this surcharge by 20%. Check the final amount in your order. A promo code is a service discount, not a promise of a payment to the client.", "Calibration price and duration are offered separately. Special circumstances are discussed before payment, and revised offers require your acceptance. Paid orders do not receive unilateral, retroactive surcharges."] },
        { id: "payment", title: "Payment procedure", list: ["Submit your request and wait for admin acceptance.", "Check the amount, duration and playing method in the order.", "Obtain payment details in that order's chat. If paying in another currency, agree on the amount and conversion before transferring; your bank may charge its own fees.", "Transfer the agreed amount. If necessary, provide the date and amount, hiding unrelated personal information from payment evidence.", "Wait for the admin to confirm receipt. A payment screenshot alone does not establish that funds arrived.", "Submit details in the dedicated form or agree on your DUO schedule. Delivery time starts after this step."], paragraphs: ["An automatic payment provider is not connected yet. The site does not debit cards, store their credentials or create subscriptions. Do not pay using unsolicited messages outside the agreed chat without checking the recipient."] },
        { id: "cancel", title: "Cancellation before delivery starts", paragraphs: ["Before payment is confirmed, you can cancel in your account and give a reason. If funds have already been transferred but are not marked as received, tell the admin and request reconciliation: cancelling a request does not automatically reverse a bank transfer.", "After payment, send a cancellation request in chat or to the public email. If work has not begun and there are no evidenced order-related expenses, a full refund is proposed. Any legally permitted actual expenses must be justified, with a calculation of the refund amount. There is no fixed cancellation penalty."] },
        { id: "partial", title: "Work in progress, delays and complaints", paragraphs: ["Ending an order already in progress requires consideration of the delivered scope, evidenced expenses and mandatory customer rights. The refund depends on the circumstances; a calculation is provided on request. Starting work alone does not make the entire payment non-refundable.", "For a delay or inability to deliver, say whether you want to discuss continuation, a revised deadline or ending the service. Reasons and arrangements are recorded in chat and order history. A bonus does not replace a refund or other remedy required by law.", "If delivery is defective or does not match the agreed result, describe the issue and provide relevant evidence without passwords. Platform restrictions are reviewed based on the specific facts; risk acknowledgement does not remove the provider's responsibility for their own breaches."] },
        { id: "refund", title: "Refund process", paragraphs: ["Provide the order number, account email, payment date and amount, reason and requested outcome. Use the order chat or owner contact at the end of this document. Details for returning funds to the original payer may need to be agreed securely; banking passwords, CVC/CVV and SMS codes are not required.", "Refunds currently use manual bank transfers, not automatic website payments. The admin communicates the decision, calculation and transfer information. Where possible, funds are returned to the original payer through the original method. Bank processing affects arrival time; mandatory statutory timelines and requirements take priority.", "A refund mark in your account records an operation and does not itself move money. If funds have not arrived, request a check. Duplicate payments, amount mistakes and disputes about receipt are also reviewed against the actual payments."] },
        { id: "rights", title: "Customer rights and draft status", paragraphs: ["These payment, cancellation and refund rules are a draft. They do not restrict rights that cannot be waived by agreement, and do not replace an approved contract with an identified provider. Mandatory law prevails over conflicting provisions.", "New rules do not retroactively worsen an already paid order. Enquiries are first discussed with the owner; rights to contact a competent authority or court remain."], links: [{ label: "Terms of use", href: "terms" }] },
      ],
    },
    cookies: {
      description: "Cookies and browser records used by CS2 Boost, and how to manage saved settings and drafts.",
      summary: ["Cookies support sign-in", "Drafts stay in the current tab", "No third-party advertising pixels are integrated"],
      sections: [
        { id: "types", title: "Cookies and local storage", paragraphs: ["Your browser sends cookies to the server to maintain sign-in. localStorage retains browser settings between visits; sessionStorage holds data for the current tab. Clearing these records affects convenience but does not delete your account or server order history.", "This page describes the current implementation. It is a draft that must be agreed alongside the privacy policy and any required consent settings."] },
        { id: "inventory", title: "Storage inventory", table: { headings: ["Record", "Purpose", "Duration"], rows: [["__Host-cs2_session", "Sign-in cookie. HttpOnly, Secure and SameSite=Lax on HTTPS. Contains a random session identifier.", "Up to 7 days; ends on sign-out or session revocation."], ["__Host-cs2_mfa", "Intermediate cookie for two-factor sign-in verification.", "Up to 5 minutes."], ["cs2-lang · localStorage", "Selected interface language.", "Until changed or cleared by the browser."], ["cs2-draft, cs2-promo · sessionStorage", "Request settings and promo code to preserve configuration between steps.", "For the tab session; the order draft is cleared after submission."], ["Message drafts · sessionStorage", "Unsent text in an order or support chat.", "For the tab session or until the draft is cleared."], ["cs2-campaign · sessionStorage", "UTM source, medium, campaign and link variant for request statistics.", "For the tab session; details may be saved with the submitted order."]] }, paragraphs: ["In a local HTTP preview, sign-in cookies are named cs2_session and cs2_mfa. This does not mean the published service should be used without HTTPS."] },
        { id: "tracking", title: "Statistics and third-party services", paragraphs: ["Google Analytics, Yandex Metrica and third-party advertising pixels are not integrated in this version. Internal source statistics use advertising link parameters saved with requests. Having no third-party pixels does not mean the service processes no technical information.", "If additional analytics, advertising tracking or other optional technologies are introduced, their scope and retention must be disclosed in advance. Where consent is required, activation must depend on a separate choice, not merely viewing this page."] },
        { id: "control", title: "Managing browser records", list: ["Find cs2-boosts.ru site data in browser settings to clear cookies and storage for this site.", "Clearing a sign-in cookie ends that browser session. Use account settings to revoke sessions on other devices.", "Clearing localStorage resets the selected language. Clearing sessionStorage removes the saved request, promo code and unsent message drafts for the tab.", "Blocking cookies entirely may prevent sign-in and account features. General information and documents can be viewed without an account.", "Request deletion of server information separately from the owner: clearing your browser does not delete order history."], links: [{ label: "Privacy policy", href: "privacy" }] },
      ],
    },
  },
};
